### ISSUE TITLE
日本語訳　What is Proof-of-Importance (POI) and Why Is It Better, and What Is Vesting?

### ISSUE THREAD

**Issue by CoffeeTimes** [NEMJPManual/NEMJPManual.github.io#11]
I'd like to add this document below to JPManual:)
https://docs.google.com/document/d/15y7PKKNk1Q4Z3hC1HiOVhdofYH4d4HmNx7eh_B6XjuA/edit

Thank you.

**Comment by him0** [comment]
日本語化プロジェクトなので日本語で大丈夫です😄

自分が担当させていただきます。

**Comment by him0** [comment]
@CoffeeTimes
クレジットとして、名前の表記をしたいです。
アカウント等載せたいのものがあればどうぞ、CoffeeTimes という名前だけでいいならそうします。

**Comment by him0** [comment]
プルリク作成してレビュー待ちです。
レビューが終わって問題なければマージします。

**Comment by CoffeeTimes** [comment]
名前入力しました。
よろしくお願いします。

**Comment by him0** [comment]
@CoffeeTimes さん
Github のアカウント表示を希望ということでしょうか？

**Comment by CoffeeTimes** [comment]
@him0 すっからかんですが、表示希望です！

**Comment by him0** [comment]
記事登載完了したので、close します。
