### ISSUE TITLE
手数料 に関する説明の追加

### ISSUE THREAD

**Issue by GodTanu** [NEMJPManual/NEMJPManual.github.io#12]
手数料に関して疑問があるので以下の解説を参考に資料化したいです
http://bob.nem.ninja/docs/#transaction-fees

**Comment by him0** [comment]
タスクとしては、
- [x] 原文の翻訳 おおざっぱ
- [x] 修正
- [x] ページの作成
- [x] レビュー
- [x] マージ

といった感じで進めたいと思います。

とりあえずGoogle Drive に[翻訳用の原稿](https://docs.google.com/document/d/1dd0nYF-vddJDd7boyXhhZlqw9EXAv-JwXCl9UgvFdi8/edit#)作りました。

自分も、少しずつ翻訳するので、協力お願いします。

**Comment by him0** [comment]
@tomotomo9696 さんをアサインしました。
ページ作成お願いします。
環境構築等で、困ったらチャットください

**Comment by tomotomo9696** [comment]
取りあえずざっとコピーして細かいところ修正したものをPRしました。
なんかマークダウンがうまくいかず29行目がひどいことになってますが。

**Comment by tomotomo9696** [comment]
#14 にてページを追加、 @him0 さんのレビューが完了しましたのでマージ後クローズします。
