### ISSUE TITLE
NEMのtechrefをこのOrganizationに移そうと思うのですがよろしいでしょうか

### ISSUE THREAD

**Issue by joemphilips** [NEMJPManual/NEMJPManual.github.io#16]
個人のリポジトリで翻訳をしていたのですが、統合してしまったほうがユーザーフレンドリーだと思います。
https://github.com/joemphilips/NEM_Technical_reference_JA

もしよろしければforkして移そうかと思いますので、私をメンバーに加えていただけないでしょうか。

**Comment by joemphilips** [comment]
あるいはそちらで行っていただいても結構です。

**Comment by tomotomo9696** [comment]
統合大歓迎です、わざわざありがとうございます。
メンバー招待を送りましたのでご確認ください。

取敢えず NEMJPManual/NEM_Technical_reference_JA にclone しておきましたが、
実際にこれらをサイトにどう配置するかはデザイン担当した @him0 さんに相談しないといけません。

**Comment by joemphilips** [comment]
ありがとうございます。
文書のスタイルまで統一してサイトに組み込む必要はなく、以下の2点で十分だと個人的には思います。が、お任せします。

1. Github側を統合(同じOrganizationで管理)
2. NEMJPManualからTechrefのGitbookにリンクを貼る。

**Comment by him0** [comment]
なるほど要件把握しました．

タスクとしたは，
- [x] Github側を統合(同じOrganizationで管理)
- [x] NEMJPManualからTechrefのGitbookにリンクを貼る。

NEMJPManual からリンク貼らせもらいます．

**Comment by tomotomo9696** [comment]
#17 をマージして、トップページにリンクが反映されました。
トップページのメンバー紹介追加どうしましょう？

**Comment by joemphilips** [comment]
#19 で私のメンバー紹介を追加しました

**Comment by joemphilips** [comment]
#17  #19 で変更が完了したのでCloseします。
